# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scores.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tensor_pb2 as tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scores.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cscores.proto\x1a\x0ctensor.proto\"H\n\x13SentenceScoresProto\x12\x13\n\x0bsentence_id\x18\x01 \x01(\r\x12\x1c\n\x06scores\x18\x02 \x01(\x0b\x32\x0c.TensorProto\"6\n\x0bScoresProto\x12\'\n\tsentences\x18\x01 \x03(\x0b\x32\x14.SentenceScoresProto')
  ,
  dependencies=[tensor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENTENCESCORESPROTO = _descriptor.Descriptor(
  name='SentenceScoresProto',
  full_name='SentenceScoresProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence_id', full_name='SentenceScoresProto.sentence_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scores', full_name='SentenceScoresProto.scores', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=102,
)


_SCORESPROTO = _descriptor.Descriptor(
  name='ScoresProto',
  full_name='ScoresProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='ScoresProto.sentences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=158,
)

_SENTENCESCORESPROTO.fields_by_name['scores'].message_type = tensor__pb2._TENSORPROTO
_SCORESPROTO.fields_by_name['sentences'].message_type = _SENTENCESCORESPROTO
DESCRIPTOR.message_types_by_name['SentenceScoresProto'] = _SENTENCESCORESPROTO
DESCRIPTOR.message_types_by_name['ScoresProto'] = _SCORESPROTO

SentenceScoresProto = _reflection.GeneratedProtocolMessageType('SentenceScoresProto', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCESCORESPROTO,
  __module__ = 'scores_pb2'
  # @@protoc_insertion_point(class_scope:SentenceScoresProto)
  ))
_sym_db.RegisterMessage(SentenceScoresProto)

ScoresProto = _reflection.GeneratedProtocolMessageType('ScoresProto', (_message.Message,), dict(
  DESCRIPTOR = _SCORESPROTO,
  __module__ = 'scores_pb2'
  # @@protoc_insertion_point(class_scope:ScoresProto)
  ))
_sym_db.RegisterMessage(ScoresProto)


# @@protoc_insertion_point(module_scope)
