# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensor.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0ctensor.proto\":\n\x12L2WeightDecayProto\x12\x14\n\x0cweight_decay\x18\x01 \x01(\x02\x12\x0e\n\x06lambda\x18\x02 \x01(\x02\"$\n\x0f\x44imensionsProto\x12\x11\n\tdimension\x18\x01 \x03(\r\"F\n\x0bTensorProto\x12$\n\ndimensions\x18\x01 \x01(\x0b\x32\x10.DimensionsProto\x12\x11\n\x05value\x18\x02 \x03(\x02\x42\x02\x10\x01\"S\n\x0eParameterProto\x12$\n\ndimensions\x18\x01 \x01(\x0b\x32\x10.DimensionsProto\x12\x1b\n\x05value\x18\x02 \x03(\x0b\x32\x0c.TensorProto\"\x86\x01\n\nModelProto\x12\"\n\tparameter\x18\x01 \x03(\x0b\x32\x0f.ParameterProto\x12)\n\x10lookup_parameter\x18\x02 \x03(\x0b\x32\x0f.ParameterProto\x12)\n\x0cweight_decay\x18\x03 \x01(\x0b\x32\x13.L2WeightDecayProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_L2WEIGHTDECAYPROTO = _descriptor.Descriptor(
  name='L2WeightDecayProto',
  full_name='L2WeightDecayProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight_decay', full_name='L2WeightDecayProto.weight_decay', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lambda', full_name='L2WeightDecayProto.lambda', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=74,
)


_DIMENSIONSPROTO = _descriptor.Descriptor(
  name='DimensionsProto',
  full_name='DimensionsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='DimensionsProto.dimension', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=112,
)


_TENSORPROTO = _descriptor.Descriptor(
  name='TensorProto',
  full_name='TensorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='TensorProto.dimensions', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='TensorProto.value', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=184,
)


_PARAMETERPROTO = _descriptor.Descriptor(
  name='ParameterProto',
  full_name='ParameterProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='ParameterProto.dimensions', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ParameterProto.value', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=269,
)


_MODELPROTO = _descriptor.Descriptor(
  name='ModelProto',
  full_name='ModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter', full_name='ModelProto.parameter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lookup_parameter', full_name='ModelProto.lookup_parameter', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight_decay', full_name='ModelProto.weight_decay', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=406,
)

_TENSORPROTO.fields_by_name['dimensions'].message_type = _DIMENSIONSPROTO
_PARAMETERPROTO.fields_by_name['dimensions'].message_type = _DIMENSIONSPROTO
_PARAMETERPROTO.fields_by_name['value'].message_type = _TENSORPROTO
_MODELPROTO.fields_by_name['parameter'].message_type = _PARAMETERPROTO
_MODELPROTO.fields_by_name['lookup_parameter'].message_type = _PARAMETERPROTO
_MODELPROTO.fields_by_name['weight_decay'].message_type = _L2WEIGHTDECAYPROTO
DESCRIPTOR.message_types_by_name['L2WeightDecayProto'] = _L2WEIGHTDECAYPROTO
DESCRIPTOR.message_types_by_name['DimensionsProto'] = _DIMENSIONSPROTO
DESCRIPTOR.message_types_by_name['TensorProto'] = _TENSORPROTO
DESCRIPTOR.message_types_by_name['ParameterProto'] = _PARAMETERPROTO
DESCRIPTOR.message_types_by_name['ModelProto'] = _MODELPROTO

L2WeightDecayProto = _reflection.GeneratedProtocolMessageType('L2WeightDecayProto', (_message.Message,), dict(
  DESCRIPTOR = _L2WEIGHTDECAYPROTO,
  __module__ = 'tensor_pb2'
  # @@protoc_insertion_point(class_scope:L2WeightDecayProto)
  ))
_sym_db.RegisterMessage(L2WeightDecayProto)

DimensionsProto = _reflection.GeneratedProtocolMessageType('DimensionsProto', (_message.Message,), dict(
  DESCRIPTOR = _DIMENSIONSPROTO,
  __module__ = 'tensor_pb2'
  # @@protoc_insertion_point(class_scope:DimensionsProto)
  ))
_sym_db.RegisterMessage(DimensionsProto)

TensorProto = _reflection.GeneratedProtocolMessageType('TensorProto', (_message.Message,), dict(
  DESCRIPTOR = _TENSORPROTO,
  __module__ = 'tensor_pb2'
  # @@protoc_insertion_point(class_scope:TensorProto)
  ))
_sym_db.RegisterMessage(TensorProto)

ParameterProto = _reflection.GeneratedProtocolMessageType('ParameterProto', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERPROTO,
  __module__ = 'tensor_pb2'
  # @@protoc_insertion_point(class_scope:ParameterProto)
  ))
_sym_db.RegisterMessage(ParameterProto)

ModelProto = _reflection.GeneratedProtocolMessageType('ModelProto', (_message.Message,), dict(
  DESCRIPTOR = _MODELPROTO,
  __module__ = 'tensor_pb2'
  # @@protoc_insertion_point(class_scope:ModelProto)
  ))
_sym_db.RegisterMessage(ModelProto)


_TENSORPROTO.fields_by_name['value'].has_options = True
_TENSORPROTO.fields_by_name['value']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
